from django.urls import path

from .views import (
    ExtensionPermissionCatalogView,
    ModuleCatalogView,
    ModuleJobView,
    ModulePackageInspectView,
    ModulePackageStageView,
    ModulePackageInstallView,
    ModuleRemoveView,
    RoleExtensionPermissionsView,
    TotpQrView,
    SystemUpdateStatusView,
    SystemUpdatePackageInspectView,
    SystemUpdatePackageStageView,
    SystemUpdatePackageInstallView,
    SystemUpdateJobView,
    SystemUpdateOnlineStatusView,
    SystemUpdateBranchesView,
    SystemUpdateOnlineStageView,
    UiContextView,
)

urlpatterns = [
    path("ui/context/", UiContextView.as_view(), name="tec-tac-ui-context"),
    path("system/updates/", SystemUpdateStatusView.as_view(), name="tec-tac-system-update-status"),
    path("system/updates/packages/inspect/", SystemUpdatePackageInspectView.as_view(), name="tec-tac-system-update-package-inspect"),
    path("system/updates/packages/<uuid:upload_id>/", SystemUpdatePackageStageView.as_view(), name="tec-tac-system-update-package-stage"),
    path("system/updates/packages/<uuid:upload_id>/install/", SystemUpdatePackageInstallView.as_view(), name="tec-tac-system-update-package-install"),
    path("system/updates/jobs/<uuid:job_id>/", SystemUpdateJobView.as_view(), name="tec-tac-system-update-job"),
    path("system/updates/online/", SystemUpdateOnlineStatusView.as_view(), name="tec-tac-system-update-online-status"),
    path("system/updates/branches/", SystemUpdateBranchesView.as_view(), name="tec-tac-system-update-branches"),
    path("system/updates/online/stage/", SystemUpdateOnlineStageView.as_view(), name="tec-tac-system-update-online-stage"),
    path("auth/totp/qr/", TotpQrView.as_view(), name="tec-tac-totp-qr"),
    path("access/extensions/", ExtensionPermissionCatalogView.as_view(), name="tec-tac-extension-permissions"),
    path("modules/", ModuleCatalogView.as_view(), name="tec-tac-module-catalog"),
    path("modules/packages/inspect/", ModulePackageInspectView.as_view(), name="tec-tac-module-package-inspect"),
    path("modules/packages/<uuid:upload_id>/", ModulePackageStageView.as_view(), name="tec-tac-module-package-stage"),
    path("modules/packages/<uuid:upload_id>/install/", ModulePackageInstallView.as_view(), name="tec-tac-module-package-install"),
    path("modules/<str:plugin_id>/remove/", ModuleRemoveView.as_view(), name="tec-tac-module-remove"),
    path("modules/jobs/<uuid:job_id>/", ModuleJobView.as_view(), name="tec-tac-module-job"),
    path(
        "access/roles/<int:role_id>/permissions/",
        RoleExtensionPermissionsView.as_view(),
        name="tec-tac-role-extension-permissions",
    ),
]
