from django.urls import path
from .views import (
    ExtensionPermissionCatalogView, ModuleCatalogView, ModuleJobView,
    ModulePackageInspectView, ModulePackageStageView, ModulePackageInstallView,
    ModuleRemoveView, RoleExtensionPermissionsView, TotpQrView,
    SystemUpdateStatusView, SystemUpdatePackageInspectView, SystemUpdatePackageStageView,
    SystemUpdatePackageInstallView, SystemUpdateJobView, SystemUpdateOnlineStatusView,
    SystemUpdateBranchesView, SystemUpdateOnlineStageView, UiContextView,
)
from .module_repository_views import (
    ModuleRepositoryListView, ModuleRepositoryDetailView, ModuleRepositorySyncView,
    ModuleRepositorySyncAllView, ModuleOnlineCatalogView, ModuleOnlineStageView,
)
from .module_v2_views import (
    ModuleV2CatalogView, ModuleV2InspectView, ModuleV2StageView, ModuleV2InstallView,
    ModuleV2StateView, ModuleV2VisibilityView, ModuleV2RemoveCheckView, ModuleV2JobView,
)
urlpatterns = [
    path("ui/context/", UiContextView.as_view(), name="tec-tac-ui-context"),
    path("system/updates/", SystemUpdateStatusView.as_view(), name="tec-tac-system-update-status"),
    path("system/updates/packages/inspect/", SystemUpdatePackageInspectView.as_view(), name="tec-tac-system-update-package-inspect"),
    path("system/updates/packages/<uuid:upload_id>/", SystemUpdatePackageStageView.as_view(), name="tec-tac-system-update-package-stage"),
    path("system/updates/packages/<uuid:upload_id>/install/", SystemUpdatePackageInstallView.as_view(), name="tec-tac-system-update-package-install"),
    path("system/updates/jobs/<uuid:job_id>/", SystemUpdateJobView.as_view(), name="tec-tac-system-update-job"),
    path("system/updates/online/", SystemUpdateOnlineStatusView.as_view(), name="tec-tac-system-update-online-status"),
    path("system/updates/branches/", SystemUpdateBranchesView.as_view(), name="tec-tac-system-update-branches"),
    path("system/updates/online/stage/", SystemUpdateOnlineStageView.as_view(), name="tec-tac-system-update-online-stage"),
    path("auth/totp/qr/", TotpQrView.as_view(), name="tec-tac-totp-qr"),
    path("access/extensions/", ExtensionPermissionCatalogView.as_view(), name="tec-tac-extension-permissions"),
    path("modules/", ModuleCatalogView.as_view(), name="tec-tac-module-catalog"),
    path("modules/packages/inspect/", ModulePackageInspectView.as_view(), name="tec-tac-module-package-inspect"),
    path("modules/packages/<uuid:upload_id>/", ModulePackageStageView.as_view(), name="tec-tac-module-package-stage"),
    path("modules/packages/<uuid:upload_id>/install/", ModulePackageInstallView.as_view(), name="tec-tac-module-package-install"),
    path("modules/<str:plugin_id>/remove/", ModuleRemoveView.as_view(), name="tec-tac-module-remove"),
    path("modules/jobs/<uuid:job_id>/", ModuleJobView.as_view(), name="tec-tac-module-job"),
    path("modules/repositories/", ModuleRepositoryListView.as_view(), name="tec-tac-module-repositories"),
    path("modules/repositories/sync/", ModuleRepositorySyncAllView.as_view(), name="tec-tac-module-repositories-sync"),
    path("modules/repositories/<str:repository_id>/", ModuleRepositoryDetailView.as_view(), name="tec-tac-module-repository-detail"),
    path("modules/repositories/<str:repository_id>/sync/", ModuleRepositorySyncView.as_view(), name="tec-tac-module-repository-sync"),
    path("modules/catalog/online/", ModuleOnlineCatalogView.as_view(), name="tec-tac-module-online-catalog"),
    path("modules/catalog/online/stage/", ModuleOnlineStageView.as_view(), name="tec-tac-module-online-stage"),
    path("modules/v2/", ModuleV2CatalogView.as_view(), name="tec-tac-module-v2-catalog"),
    path("modules/v2/packages/inspect/", ModuleV2InspectView.as_view(), name="tec-tac-module-v2-inspect"),
    path("modules/v2/packages/<uuid:upload_id>/", ModuleV2StageView.as_view(), name="tec-tac-module-v2-stage"),
    path("modules/v2/packages/<uuid:upload_id>/install/", ModuleV2InstallView.as_view(), name="tec-tac-module-v2-install"),
    path("modules/v2/<str:plugin_id>/state/", ModuleV2StateView.as_view(), name="tec-tac-module-v2-state"),
    path("modules/v2/<str:plugin_id>/visibility/", ModuleV2VisibilityView.as_view(), name="tec-tac-module-v2-visibility"),
    path("modules/v2/<str:plugin_id>/remove-check/", ModuleV2RemoveCheckView.as_view(), name="tec-tac-module-v2-remove-check"),
    path("modules/v2/jobs/<uuid:job_id>/", ModuleV2JobView.as_view(), name="tec-tac-module-v2-job"),
    path("access/roles/<int:role_id>/permissions/", RoleExtensionPermissionsView.as_view(), name="tec-tac-role-extension-permissions"),
]
