# Generated by Django 4.2.30 for Tec-Tac Framework 1.15.33

from django.db import migrations, models
import tec_tac.models


class Migration(migrations.Migration):

    dependencies = [
        ("tec_tac", "0007_session_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tectacsessionsecurityconfig",
            name="trusted_proxies",
            field=models.JSONField(
                blank=True,
                default=tec_tac.models.default_session_trusted_proxies,
            ),
        ),
    ]
